### ISSUE TITLE
Add iMessage-style bevel and emboss effects to chat bubbles

### ISSUE THREAD

**Issue by iPhonz** [iPhonz/gifchat#10]
We need to update the chat bubbles to have an iMessage-like appearance with bevel and emboss effects.

Proposed CSS changes:
```css
.chat-bubble {
  /* Base styles */
  position: relative;
  padding: 12px 16px;
  border-radius: 18px;
  max-width: 70%;
  margin: 8px 0;

  /* iMessage-style bevel and emboss */
  background: linear-gradient(180deg, 
    rgba(255,255,255,0.15) 0%, 
    rgba(255,255,255,0.05) 100%);
  box-shadow: 
    inset 0 1px 1px rgba(255,255,255,0.3),
    inset 0 -1px 1px rgba(0,0,0,0.1),
    0 1px 2px rgba(0,0,0,0.1);
}

/* Sender's messages (right side) */
.chat-bubble.sent {
  background-color: #007AFF;
  margin-left: auto;
  border-bottom-right-radius: 4px;
}

/* Received messages (left side) */
.chat-bubble.received {
  background-color: #E9E9EB;
  margin-right: auto;
  border-bottom-left-radius: 4px;
  color: #000;
}

/* Enhanced bevel effect for sent messages */
.chat-bubble.sent::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 50%;
  border-radius: 18px 18px 0 0;
  background: linear-gradient(180deg, 
    rgba(255,255,255,0.25) 0%, 
    rgba(255,255,255,0) 100%);
}
```

These changes will add:
1. A subtle bevel and emboss effect using gradients and shadows
2. The characteristic iMessage bubble shape with one corner slightly pinched
3. A light reflection effect on the top of the bubbles
4. Proper spacing and alignment for both sent and received messages

Implementation steps:
1. Create new CSS file or update existing styles
2. Add these styles to the appropriate component
3. Test different message lengths and types
4. Ensure responsive behavior is maintained
